"""แทน HTML block ใน server.py"""

NEW_HTML = (
    'HTML = """<!DOCTYPE html>\n'
    '<html lang="th">\n'
    '<head>\n'
    '<meta charset="UTF-8">\n'
    '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
    '<title>PDF Scale Prototype</title>\n'
    '<style>\n'
    '*{box-sizing:border-box;margin:0;padding:0}\n'
    'body{font-family:-apple-system,sans-serif;background:#1c1c1e;color:#e5e5e7;\n'
    '     height:100vh;display:flex;flex-direction:column;overflow:hidden}\n'
    '#topbar{background:#2c2c2e;padding:6px 12px;display:flex;align-items:center;\n'
    '        gap:8px;border-bottom:1px solid #3a3a3c;flex-shrink:0}\n'
    '#topbar h1{font-size:13px;font-weight:700;white-space:nowrap}\n'
    '#upload-btn{background:#0a84ff;color:#fff;border:none;border-radius:7px;\n'
    '            padding:5px 13px;font-size:12px;font-weight:600;cursor:pointer}\n'
    '#upload-btn:hover{background:#0071e3}\n'
    '#file-input{display:none}\n'
    '.sep{width:1px;height:22px;background:#3a3a3c;flex-shrink:0}\n'
    '.tb-btn{background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.1);\n'
    '        color:#e5e5e7;border-radius:7px;padding:4px 10px;font-size:12px;cursor:pointer}\n'
    '.tb-btn:hover{background:rgba(255,255,255,.14)}\n'
    '.tb-btn.active{background:#0a84ff;border-color:#0a84ff;color:#fff}\n'
    '#scale-badge{font-size:11px;font-weight:600;padding:3px 10px;border-radius:20px;\n'
    '             background:rgba(255,69,58,.2);color:#ff453a;border:1px solid rgba(255,69,58,.3)}\n'
    '#scale-badge.ok{background:rgba(48,209,88,.15);color:#30d158;border-color:rgba(48,209,88,.3)}\n'
    '#status{font-size:11px;color:#98989f;margin-left:4px;overflow:hidden;text-overflow:ellipsis;max-width:320px;white-space:nowrap}\n'
    '#body{display:flex;flex:1;overflow:hidden}\n'
    '#thumb-strip{width:130px;min-width:130px;background:#2c2c2e;border-right:1px solid #3a3a3c;overflow-y:auto;flex-shrink:0}\n'
    '#thumb-strip::-webkit-scrollbar{width:4px}\n'
    '#thumb-strip::-webkit-scrollbar-thumb{background:#48484a;border-radius:2px}\n'
    '.thumb-item{padding:6px;cursor:pointer;border-bottom:1px solid #3a3a3c;\n'
    '            display:flex;flex-direction:column;align-items:center;gap:3px}\n'
    '.thumb-item:hover{background:rgba(255,255,255,.06)}\n'
    '.thumb-item.active{background:rgba(10,132,255,.2);border-left:3px solid #0a84ff}\n'
    '.thumb-item img{width:100%;border-radius:3px;background:#333}\n'
    '.thumb-item span{font-size:10px;color:#98989f}\n'
    '.thumb-item.active span{color:#e5e5e7}\n'
    '.thumb-scale{font-size:9px;color:#30d158;font-weight:600}\n'
    '.thumb-scale.none{color:#ff453a}\n'
    '#workspace{flex:1;overflow:hidden;position:relative;background:#111;cursor:grab}\n'
    '#workspace.drawing{cursor:crosshair}\n'
    '#cc{position:absolute;top:0;left:0;transform-origin:0 0}\n'
    'canvas{display:block}\n'
    '#infobar{background:#2c2c2e;border-top:1px solid #3a3a3c;padding:5px 14px;\n'
    '         font-size:11px;display:flex;gap:16px;align-items:center;flex-shrink:0}\n'
    '#infobar span{color:#98989f}\n'
    '#infobar b{color:#e5e5e7}\n'
    '#measure-result{color:#ffd60a;font-weight:600;margin-left:auto}\n'
    '#pin-tip{position:fixed;background:#1c1c1e;border:1px solid #3a3a3c;border-radius:8px;\n'
    '         padding:5px 10px;font-size:11px;pointer-events:none;z-index:999;display:none}\n'
    '</style>\n'
    '</head>\n'
    '<body>\n'
    '<div id="topbar">\n'
    '  <h1>\\U0001f4d0 PDF Scale</h1>\n'
    '  <label id="upload-btn">\\U0001f4c2 เปิด PDF<input id="file-input" type="file" accept=".pdf"></label>\n'
    '  <div class="sep"></div>\n'
    '  <button class="tb-btn active" id="btn-pan"  onclick="setMode(\'pan\')">\\u270b Pan</button>\n'
    '  <button class="tb-btn"        id="btn-dist" onclick="setMode(\'dist\')">\\U0001f4cf ระยะ</button>\n'
    '  <button class="tb-btn"        id="btn-area" onclick="setMode(\'area\')">\\u2b21 พื้นที่</button>\n'
    '  <button class="tb-btn"        id="btn-clr"  onclick="clearMeasures()">\\U0001f5d1</button>\n'
    '  <div class="sep"></div>\n'
    '  <span id="scale-badge">ยังไม่มีไฟล์</span>\n'
    '  <span id="status"></span>\n'
    '</div>\n'
    '<div id="body">\n'
    '  <div id="thumb-strip"></div>\n'
    '  <div id="workspace">\n'
    '    <div id="cc"><canvas id="canvas"></canvas></div>\n'
    '  </div>\n'
    '</div>\n'
    '<div id="infobar">\n'
    '  <span>Mode: <b id="lbl-mode">Pan</b></span>\n'
    '  <span>Scale: <b id="lbl-scale">\\u2014</b></span>\n'
    '  <span>หมุด: <b id="lbl-pins">\\u2014</b></span>\n'
    '  <span id="measure-result"></span>\n'
    '</div>\n'
    '<div id="pin-tip"></div>\n'
    '<script>\n'
    'let totalPages=0,curPage=1,pageData=null;\n'
    'const RS=1.5;\n'
    'let zoom=1,panX=0,panY=0,mode="pan";\n'
    'let mPts=[],mLines=[],mPolys=[];\n'
    'let isPan=false,lastMx=0,lastMy=0;\n'
    'const canvas=document.getElementById("canvas");\n'
    'const ctx=canvas.getContext("2d");\n'
    'const ws=document.getElementById("workspace");\n'
    'const cc=document.getElementById("cc");\n'
    'let bgImg=null;\n'
    '\n'
    '// upload\n'
    'document.getElementById("file-input").addEventListener("change",async e=>{\n'
    '  const file=e.target.files[0];if(!file)return;\n'
    '  setStatus("กำลังโหลด\\u2026");\n'
    '  const fd=new FormData();fd.append("file",file);\n'
    '  const res=await fetch("/upload",{method:"POST",body:fd});\n'
    '  const d=await res.json();\n'
    '  totalPages=d.pages;\n'
    '  buildThumbs(totalPages);\n'
    '  await loadPage(1);\n'
    '});\n'
    '\n'
    '// thumbnails\n'
    'function buildThumbs(n){\n'
    '  const strip=document.getElementById("thumb-strip");strip.innerHTML="";\n'
    '  for(let i=1;i<=n;i++){\n'
    '    const div=document.createElement("div");\n'
    '    div.className="thumb-item";div.id="th-"+i;\n'
    '    div.innerHTML=`<img src="/thumb/${i}" loading="lazy"><span>หน้า ${i}</span><span class="thumb-scale none" id="ts-${i}">\\u2026</span>`;\n'
    '    div.addEventListener("click",()=>loadPage(i));\n'
    '    strip.appendChild(div);\n'
    '  }\n'
    '}\n'
    'function setThumbActive(n){\n'
    '  document.querySelectorAll(".thumb-item").forEach(e=>e.classList.remove("active"));\n'
    '  const el=document.getElementById("th-"+n);\n'
    '  if(el){el.classList.add("active");el.scrollIntoView({block:"nearest"});}\n'
    '}\n'
    '\n'
    '// load page\n'
    'async function loadPage(n){\n'
    '  curPage=n;setThumbActive(n);setStatus("โหลดหน้า "+n+"\\u2026");mPts=[];\n'
    '  await new Promise(res=>{\n'
    '    const img=new Image();\n'
    '    img.onload=()=>{bgImg=img;canvas.width=img.width;canvas.height=img.height;res();};\n'
    '    img.src="/page/"+n+"?scale="+RS+"&t="+Date.now();\n'
    '  });\n'
    '  fitToWindow();redraw();\n'
    '  fetch("/analyse/"+n).then(r=>r.json()).then(d=>{\n'
    '    pageData=d;\n'
    '    const badge=document.getElementById("scale-badge");\n'
    '    const lblS=document.getElementById("lbl-scale");\n'
    '    if(d.scale){badge.className="ok";badge.textContent=d.scale.label;lblS.textContent=d.scale.label;}\n'
    '    else{badge.className="";badge.textContent="ไม่พบ scale";lblS.textContent="\\u2014";}\n'
    '    document.getElementById("lbl-pins").textContent=d.pins.length?d.pins.length+" จุด":"ไม่พบ";\n'
    '    const ts=document.getElementById("ts-"+n);\n'
    '    if(ts){if(d.scale){ts.textContent=d.scale.label;ts.className="thumb-scale";}else{ts.textContent="no scale";ts.className="thumb-scale none";}}\n'
    '    setStatus(d.pins.length?"พบหมุด "+d.pins.length+" จุด \xb7 "+(d.scale?.label??""):(d.scale?.label??"ไม่พบ scale"));\n'
    '    redraw();\n'
    '  });\n'
    '}\n'
    '\n'
    '// fit\n'
    'function fitToWindow(){\n'
    '  const W=ws.clientWidth,H=ws.clientHeight;\n'
    '  const sx=(W-20)/canvas.width,sy=(H-20)/canvas.height;\n'
    '  zoom=Math.min(sx,sy,2);\n'
    '  panX=Math.round((W-canvas.width*zoom)/2);\n'
    '  panY=Math.round((H-canvas.height*zoom)/2);\n'
    '  applyT();\n'
    '}\n'
    'function applyT(){cc.style.transform="translate("+panX+"px,"+panY+"px) scale("+zoom+")";}\n'
    '\n'
    '// draw\n'
    'const PCOLS=["#ff3b30","#ff9500","#34c759","#007aff","#af52de","#ff2d55","#5ac8fa","#ffd60a"];\n'
    'function redraw(){\n'
    '  if(!bgImg)return;\n'
    '  ctx.clearRect(0,0,canvas.width,canvas.height);\n'
    '  ctx.drawImage(bgImg,0,0);\n'
    '  if(pageData?.pins)pageData.pins.forEach((p,i)=>{\n'
    '    const x=p.cx*RS,y=p.cy*RS,c=PCOLS[i%PCOLS.length];\n'
    '    ctx.beginPath();ctx.arc(x,y,16,0,Math.PI*2);ctx.strokeStyle=c;ctx.lineWidth=3;ctx.stroke();\n'
    '    ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fillStyle=c;ctx.fill();\n'
    '    ctx.beginPath();ctx.moveTo(x-22,y);ctx.lineTo(x+22,y);ctx.moveTo(x,y-22);ctx.lineTo(x,y+22);\n'
    '    ctx.strokeStyle=c+"88";ctx.lineWidth=1.5;ctx.stroke();\n'
    '    const lbl=p.label;ctx.font="bold 14px sans-serif";\n'
    '    const tw=ctx.measureText(lbl).width;\n'
    '    ctx.fillStyle="rgba(0,0,0,.75)";ctx.fillRect(x+20,y-11,tw+10,20);\n'
    '    ctx.fillStyle=c;ctx.fillText(lbl,x+25,y+4);\n'
    '  });\n'
    '  mLines.forEach(s=>{\n'
    '    ctx.save();ctx.beginPath();ctx.moveTo(s.x0,s.y0);ctx.lineTo(s.x1,s.y1);\n'
    '    ctx.strokeStyle="#ffd60a";ctx.lineWidth=2;ctx.setLineDash([8,4]);ctx.stroke();ctx.restore();\n'
    '    drawLbl((s.x0+s.x1)/2,(s.y0+s.y1)/2,s.dist.toFixed(2)+" ม.","#ffd60a");\n'
    '  });\n'
    '  mPolys.forEach(poly=>{\n'
    '    if(poly.pts.length<2)return;\n'
    '    ctx.save();ctx.beginPath();ctx.moveTo(poly.pts[0].x,poly.pts[0].y);\n'
    '    poly.pts.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));\n'
    '    if(poly.closed)ctx.closePath();\n'
    '    ctx.strokeStyle="#30d158";ctx.lineWidth=2;ctx.stroke();\n'
    '    ctx.fillStyle="rgba(48,209,88,.1)";if(poly.closed)ctx.fill();ctx.restore();\n'
    '    if(poly.closed&&poly.area!=null){\n'
    '      const cx=poly.pts.reduce((s,p)=>s+p.x,0)/poly.pts.length;\n'
    '      const cy=poly.pts.reduce((s,p)=>s+p.y,0)/poly.pts.length;\n'
    '      drawLbl(cx,cy,poly.area.toFixed(2)+" \\u0e15\\u0e23.\\u0e21.","#30d158");\n'
    '    }\n'
    '  });\n'
    '  mPts.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fillStyle=mode==="area"?"#30d158":"#ffd60a";ctx.fill();});\n'
    '}\n'
    'function drawLbl(x,y,t,c){\n'
    '  ctx.save();ctx.font="bold 13px sans-serif";\n'
    '  const tw=ctx.measureText(t).width;\n'
    '  ctx.fillStyle="rgba(0,0,0,.78)";ctx.fillRect(x-tw/2-5,y-11,tw+10,20);\n'
    '  ctx.fillStyle=c;ctx.fillText(t,x-tw/2,y+4);ctx.restore();\n'
    '}\n'
    '\n'
    '// snap\n'
    'function snap(cx,cy,r=20){\n'
    '  if(!pageData)return{x:cx,y:cy};\n'
    '  for(const p of pageData.pins){const px=p.cx*RS,py=p.cy*RS;if(Math.hypot(cx-px,cy-py)<r)return{x:px,y:py};}\n'
    '  let best=null,bd=r;\n'
    '  for(const s of(pageData.snaps||[])){const d=Math.hypot(cx-s.x*RS,cy-s.y*RS);if(d<bd){bd=d;best={x:s.x*RS,y:s.y*RS};}}\n'
    '  return best||{x:cx,y:cy};\n'
    '}\n'
    'function ptsToM(x1,y1,x2,y2){\n'
    '  if(!pageData?.scale)return null;\n'
    '  return Math.hypot((x2-x1)/RS,(y2-y1)/RS)/pageData.scale.pts_per_m;\n'
    '}\n'
    'function polyAreaM2(pts){\n'
    '  if(!pageData?.scale)return null;\n'
    '  let a=0;for(let i=0;i<pts.length;i++){const j=(i+1)%pts.length;a+=pts[i].x*pts[j].y-pts[j].x*pts[i].y;}\n'
    '  const ppm=pageData.scale.pts_per_m*RS;return Math.abs(a)/(2*ppm*ppm);\n'
    '}\n'
    '\n'
    '// events\n'
    'function cXY(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)};}\n'
    '\n'
    'ws.addEventListener("mousedown",e=>{\n'
    '  if(mode==="pan"||e.button===1){isPan=true;lastMx=e.clientX;lastMy=e.clientY;ws.style.cursor="grabbing";return;}\n'
    '  const {x,y}=cXY(e),s=snap(x,y);\n'
    '  if(mode==="dist"){\n'
    '    mPts.push({x:s.x,y:s.y});\n'
    '    if(mPts.length===2){\n'
    '      const dist=ptsToM(mPts[0].x,mPts[0].y,mPts[1].x,mPts[1].y);\n'
    '      if(dist!=null)mLines.push({x0:mPts[0].x,y0:mPts[0].y,x1:mPts[1].x,y1:mPts[1].y,dist});\n'
    '      document.getElementById("measure-result").textContent=dist!=null?"\\U0001f4cf "+dist.toFixed(3)+" \\u0e21.":"";\n'
    '      mPts=[];\n'
    '    }\n'
    '  }else if(mode==="area"){\n'
    '    if(mPts.length>=2&&Math.hypot(s.x-mPts[0].x,s.y-mPts[0].y)<18){\n'
    '      const area=polyAreaM2(mPts);\n'
    '      const rai=area?Math.floor(area/1600):0,ngan=area?Math.floor((area%1600)/400):0,wa=area?(area%400)/4:0;\n'
    '      mPolys.push({pts:[...mPts],closed:true,area});\n'
    '      document.getElementById("measure-result").textContent=area!=null?"\\u2b21 "+area.toFixed(2)+" \\u0e15\\u0e23.\\u0e21. ("+rai+"-"+ngan+"-"+wa.toFixed(2)+" \\u0e27.)":"";\n'
    '      mPts=[];\n'
    '    }else{mPts.push({x:s.x,y:s.y});}\n'
    '  }\n'
    '  redraw();\n'
    '});\n'
    '\n'
    'ws.addEventListener("mousemove",e=>{\n'
    '  if(isPan){panX+=e.clientX-lastMx;panY+=e.clientY-lastMy;lastMx=e.clientX;lastMy=e.clientY;applyT();return;}\n'
    '  if(!pageData?.pins)return;\n'
    '  const {x,y}=cXY(e),tip=document.getElementById("pin-tip");\n'
    '  const hit=pageData.pins.find(p=>Math.hypot(x-p.cx*RS,y-p.cy*RS)<20);\n'
    '  if(hit){tip.style.display="block";tip.style.left=(e.clientX+14)+"px";tip.style.top=(e.clientY-30)+"px";tip.textContent=hit.label+" (หมุด ข.ท.ด.)";}\n'
    '  else{tip.style.display="none";}\n'
    '});\n'
    'ws.addEventListener("mouseup",()=>{isPan=false;ws.style.cursor=mode==="pan"?"grab":"crosshair";});\n'
    'ws.addEventListener("mouseleave",()=>{isPan=false;});\n'
    'ws.addEventListener("wheel",e=>{\n'
    '  e.preventDefault();\n'
    '  const r=ws.getBoundingClientRect(),fx=e.clientX-r.left,fy=e.clientY-r.top;\n'
    '  const dz=e.deltaY>0?0.85:1.18,nz=Math.max(0.08,Math.min(8,zoom*dz));\n'
    '  panX=fx-(fx-panX)*(nz/zoom);panY=fy-(fy-panY)*(nz/zoom);zoom=nz;applyT();\n'
    '},{passive:false});\n'
    '\n'
    'function setMode(m){\n'
    '  mode=m;mPts=[];\n'
    '  ["pan","dist","area"].forEach(k=>document.getElementById("btn-"+k).className="tb-btn"+(m===k?" active":""));\n'
    '  document.getElementById("lbl-mode").textContent={pan:"Pan \\u270b",dist:"\\u0e27\\u0e31\\u0e14\\u0e23\\u0e30\\u0e22\\u0e30 \\U0001f4cf",area:"\\u0e27\\u0e31\\u0e14\\u0e1e\\u0e37\\u0e49\\u0e19\\u0e17\\u0e35\\u0e48 \\u2b21"}[m];\n'
    '  ws.className=m==="pan"?"":"drawing";\n'
    '  document.getElementById("measure-result").textContent="";\n'
    '  redraw();\n'
    '}\n'
    'function clearMeasures(){mPts=[];mLines=[];mPolys=[];document.getElementById("measure-result").textContent="";redraw();}\n'
    'document.addEventListener("keydown",e=>{\n'
    '  if(e.target.tagName==="INPUT")return;\n'
    '  if(e.key==="ArrowRight"&&curPage<totalPages)loadPage(curPage+1);\n'
    '  if(e.key==="ArrowLeft"&&curPage>1)loadPage(curPage-1);\n'
    '  if(e.key==="Escape")setMode("pan");\n'
    '  if(e.key==="f"||e.key==="F")fitToWindow();\n'
    '});\n'
    'function setStatus(t){document.getElementById("status").textContent=t;}\n'
    'window.addEventListener("resize",()=>{if(bgImg)fitToWindow();});\n'
    '</script>\n'
    '</body>\n'
    '</html>"""\n'
)

with open("F:/other computers/my laptop/ai/bma-plan/proto/server.py", "r", encoding="utf-8") as f:
    lines = f.readlines()

start = next(i for i,l in enumerate(lines) if l.startswith('HTML = """'))
end   = next(i for i,l in enumerate(lines) if i > start and '</html>"""' in l)

new_lines = lines[:start] + [NEW_HTML] + lines[end+1:]
with open("F:/other computers/my laptop/ai/bma-plan/proto/server.py", "w", encoding="utf-8") as f:
    f.writelines(new_lines)
print(f"replaced HTML lines {start+1}–{end+1}")
